
#define CAPTURE2_DEVICE_NAME     L"\\Device\\Capture2"
#define CAPTURE2_SYMBOLIC_NAME   L"\\DosDevices\\Global\\Capture2"
#define CAPTURE2_DOS_NAME        "\\\\.\\Capture2"

//开启数据包捕获
#define CAPTURE2_IOCTL_ONE CTL_CODE(FILE_DEVICE_NETWORK, 0x801, METHOD_BUFFERED, FILE_ANY_ACCESS)
//关闭数据包捕获
#define CAPTURE2_IOCTL_TWO CTL_CODE(FILE_DEVICE_NETWORK, 0x802, METHOD_BUFFERED, FILE_ANY_ACCESS)
//获取一个数据包数据
#define CAPTURE2_IOCTL_THREE CTL_CODE(FILE_DEVICE_NETWORK, 0x803, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define CAPTURE2_IOCTL_FOUR CTL_CODE(FILE_DEVICE_NETWORK, 0x804, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define CAPTURE2_IOCTL_FIVE CTL_CODE(FILE_DEVICE_NETWORK, 0x805, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define CAPTURE2_IOCTL_SIX CTL_CODE(FILE_DEVICE_NETWORK, 0x806, METHOD_BUFFERED, FILE_ANY_ACCESS)
//开启ip拦截
#define CAPTURE2_IOCTL_SEVEN CTL_CODE(FILE_DEVICE_NETWORK, 0x807, METHOD_BUFFERED, FILE_ANY_ACCESS)
//关闭ip拦截
#define CAPTURE2_IOCTL_EIGHT CTL_CODE(FILE_DEVICE_NETWORK, 0x808, METHOD_BUFFERED, FILE_ANY_ACCESS)
//增加ip拦截规则
#define CAPTURE2_IOCTL_NINE CTL_CODE(FILE_DEVICE_NETWORK, 0x809, METHOD_BUFFERED, FILE_ANY_ACCESS)
//清空ip拦截规则
#define CAPTURE2_IOCTL_TEN CTL_CODE(FILE_DEVICE_NETWORK, 0x8010, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define CAPTURE2_IOCTL_ELEVEN CTL_CODE(FILE_DEVICE_NETWORK, 0x8011, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define CAPTURE2_IOCTL_TWELVE CTL_CODE(FILE_DEVICE_NETWORK, 0x8012, METHOD_BUFFERED, FILE_ANY_ACCESS)









//日志
typedef struct _Capture2_RECODE {
	UINT32 time;
	int direction;
	int protocol;
	UINT32 srcIp;
	int srcPort;
	UINT32 dstIp;
	int sdtPort;
	char path[255];
} Capture2_RECODE,*PCapture2_RECODE;


